name: Python Tests

on:
  push:
    branches:
      - tests
      - main
      - release
  pull_request:
    branches:
      - main
      - release
      - develop

env:
  STUDENT_NAME: "Рахимкулов Даниил Роебртович"
  GROUP_NUMBER: "M3115"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print student info
        run: |
          echo "ФИО: ${{ env.STUDENT_NAME }}"
          echo "Группа: ${{ env.GROUP_NUMBER }}"
          echo "GitHub username: ${{ github.actor }}"

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then
            pip install -r tests/requirements.txt
          fi

      - name: Run tests
        run: |
          python -m unittest discover tests/ "tests_*.py" -v


